### ISSUE TITLE
Rename repo to better reflect usage and intentions

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/pathogen-repo-template#17]
_Originally proposed by Trevor on [Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1698956318987689)_

> This may be overly close to a semantic distinction, but I wonder if instead of calling it https://github.com/nextstrain/pathogen-repo-template, we called it `pathogen-repo-interface` (or `pathogen-repo-schema`) instead. This feels perhaps closer to the intent. Again, I would imagine a "template" to basically be peppered with `{PATHOGEN}` placeholders that you just need to find and replace and then it will run. Vs the current skeleton that specifies file structure, groups of Snakemake rules, etc...

Potential names that were proposed in the Slack thread

- pathogen-repo-interface
- pathogen-repo-schema
- pathogen-repo-convention
- pathogen-repo-layout
- pathogen-repo-framework
- pathogen-repo-guide

**Comment by tsibley** [comment]
+1 for pathogen-repo-layout

**Comment by tsibley** [comment]
@nextstrain/core Can we rename this before we get much further? I'd advocate for `pathogen-repo-layout`. (Or barring that, decide definitely _not_ to rename it?)

**Comment by victorlin** [comment]
+1 for pathogen-repo-layout

**Comment by joverlee521** [comment]
+1 for `pathogen-repo-layout`

**Comment by DOH-LMT2303** [comment]
What about `pathogen-repo-blueprint` as in a software blueprint that is used for building, configuring, and documenting the architecture of a given pathogen build.

**Comment by rneher** [comment]
my vote is for `pathogen-repo-template`. GitHub defines templates as

"...[from a] template repository [a user] can create a new repository based on the template with the same directory structure, branches, and files."

https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template#about-repository-templates

Isn't this exactly what we are setting up?

**Comment by trvrb** [comment]
I like 
- pathogen-repo-framework
- pathogen-repo-layout
- pathogen-repo-guide
- pathogen-repo-convention
about equally well. Even if pathogen-repo-template is technically correct according to GitHub guidelines, I think that most people would expect a "template" to be a fill-in-the-blanks solution, which this is not. I think the four above options all convey something closer to what this is supposed to be.

**Comment by victorlin** [comment]
> What about `pathogen-repo-blueprint` as in a software blueprint that is used for building, configuring, and documenting the architecture of a given pathogen build.

I think of blueprints as covering more details and used to create exact copies of the outlined design. That's not the purpose of this repo, which should provide space for pathogen-specific implementation details.

To frame my thinking, I searched [blueprint](https://www.google.com/search?q=blueprint&tbm=isch) and [layout](https://www.google.com/search?q=layout&tbm=isch) on Google Images. It's apparent that "layout" covers general spatial placement and order, while "blueprint" covers details such as exact dimensions of architecture.

**Comment by joverlee521** [comment]
I do want to note that the ingest directory is currently much more detailed than just a layout. It includes [rules](https://github.com/nextstrain/pathogen-repo-template/tree/cd1ef12987b71a1fd8dd73eafb8c8c4bd4e6d817/ingest/rules), [default configs](https://github.com/nextstrain/pathogen-repo-template/blob/cd1ef12987b71a1fd8dd73eafb8c8c4bd4e6d817/ingest/defaults/config.yaml), [build-configs](https://github.com/nextstrain/pathogen-repo-template/tree/cd1ef12987b71a1fd8dd73eafb8c8c4bd4e6d817/ingest/build-configs/nextstrain-automation), etc. Essentially, it can be a fill in the NCBI taxon ID and run ingest "template".  

With the expectation that this repo will just be a guide for the general layout, should the ingest workflow details be moved to a separate repo or is it fine to keep the details here?

**Comment by tsibley** [comment]
For simplicity of usage, I'd say keep it here. The more base implementation we can provide out of the box, the better!

**Comment by tsibley** [comment]
If the repo's a mix of skeletal layout + templated implementation + docs + etc. I'd think to veer towards "guide" as the descriptor, as in `pathogen-repo-guide`. Or leave it as `pathogen-repo-template`. Or just call it `pathogen-repo`. (But we should get on with it and just pick!)

**Comment by tsibley** [comment]
I put making a decision [on the agenda for tomorrow](https://docs.google.com/document/d/1NUs9gtrFxR1-6Xiynq57oHz4tATNqpOkGcMydx9_D4k/edit#bookmark=id.iileu11cy25m).

**Comment by joverlee521** [comment]
Voted to rename to `pathogen-repo-guide` in the internal Nextstrain meeting today.
